alphabet = [
    "_",
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
]
initial_state = "A"
final_states = ["B"]

[[states]]
name = "A"
transitions = [
    { symbol = "_", next_state = "B" },

    { symbol = "a", next_state = "B" },
    { symbol = "b", next_state = "B" },
    { symbol = "c", next_state = "B" },
    { symbol = "d", next_state = "B" },
    { symbol = "e", next_state = "B" },
    { symbol = "f", next_state = "B" },
    { symbol = "g", next_state = "B" },
    { symbol = "h", next_state = "B" },
    { symbol = "i", next_state = "B" },
    { symbol = "j", next_state = "B" },
    { symbol = "k", next_state = "B" },
    { symbol = "l", next_state = "B" },
    { symbol = "m", next_state = "B" },
    { symbol = "n", next_state = "B" },
    { symbol = "o", next_state = "B" },
    { symbol = "p", next_state = "B" },
    { symbol = "q", next_state = "B" },
    { symbol = "r", next_state = "B" },
    { symbol = "s", next_state = "B" },
    { symbol = "t", next_state = "B" },
    { symbol = "u", next_state = "B" },
    { symbol = "v", next_state = "B" },
    { symbol = "w", next_state = "B" },
    { symbol = "x", next_state = "B" },
    { symbol = "y", next_state = "B" },
    { symbol = "z", next_state = "B" },

    { symbol = "A", next_state = "B" },
    { symbol = "B", next_state = "B" },
    { symbol = "C", next_state = "B" },
    { symbol = "D", next_state = "B" },
    { symbol = "E", next_state = "B" },
    { symbol = "F", next_state = "B" },
    { symbol = "G", next_state = "B" },
    { symbol = "H", next_state = "B" },
    { symbol = "I", next_state = "B" },
    { symbol = "J", next_state = "B" },
    { symbol = "K", next_state = "B" },
    { symbol = "L", next_state = "B" },
    { symbol = "M", next_state = "B" },
    { symbol = "N", next_state = "B" },
    { symbol = "O", next_state = "B" },
    { symbol = "P", next_state = "B" },
    { symbol = "Q", next_state = "B" },
    { symbol = "R", next_state = "B" },
    { symbol = "S", next_state = "B" },
    { symbol = "T", next_state = "B" },
    { symbol = "U", next_state = "B" },
    { symbol = "V", next_state = "B" },
    { symbol = "W", next_state = "B" },
    { symbol = "X", next_state = "B" },
    { symbol = "Y", next_state = "B" },
    { symbol = "Z", next_state = "B" },
]

[[states]]
name = "B"
transitions = [
    { symbol = "_", next_state = "B" },

    { symbol = "0", next_state = "B" },
    { symbol = "1", next_state = "B" },
    { symbol = "2", next_state = "B" },
    { symbol = "3", next_state = "B" },
    { symbol = "4", next_state = "B" },
    { symbol = "5", next_state = "B" },
    { symbol = "6", next_state = "B" },
    { symbol = "7", next_state = "B" },
    { symbol = "8", next_state = "B" },
    { symbol = "9", next_state = "B" },

    { symbol = "a", next_state = "B" },
    { symbol = "b", next_state = "B" },
    { symbol = "c", next_state = "B" },
    { symbol = "d", next_state = "B" },
    { symbol = "e", next_state = "B" },
    { symbol = "f", next_state = "B" },
    { symbol = "g", next_state = "B" },
    { symbol = "h", next_state = "B" },
    { symbol = "i", next_state = "B" },
    { symbol = "j", next_state = "B" },
    { symbol = "k", next_state = "B" },
    { symbol = "l", next_state = "B" },
    { symbol = "m", next_state = "B" },
    { symbol = "n", next_state = "B" },
    { symbol = "o", next_state = "B" },
    { symbol = "p", next_state = "B" },
    { symbol = "q", next_state = "B" },
    { symbol = "r", next_state = "B" },
    { symbol = "s", next_state = "B" },
    { symbol = "t", next_state = "B" },
    { symbol = "u", next_state = "B" },
    { symbol = "v", next_state = "B" },
    { symbol = "w", next_state = "B" },
    { symbol = "x", next_state = "B" },
    { symbol = "y", next_state = "B" },
    { symbol = "z", next_state = "B" },

    { symbol = "A", next_state = "B" },
    { symbol = "B", next_state = "B" },
    { symbol = "C", next_state = "B" },
    { symbol = "D", next_state = "B" },
    { symbol = "E", next_state = "B" },
    { symbol = "F", next_state = "B" },
    { symbol = "G", next_state = "B" },
    { symbol = "H", next_state = "B" },
    { symbol = "I", next_state = "B" },
    { symbol = "J", next_state = "B" },
    { symbol = "K", next_state = "B" },
    { symbol = "L", next_state = "B" },
    { symbol = "M", next_state = "B" },
    { symbol = "N", next_state = "B" },
    { symbol = "O", next_state = "B" },
    { symbol = "P", next_state = "B" },
    { symbol = "Q", next_state = "B" },
    { symbol = "R", next_state = "B" },
    { symbol = "S", next_state = "B" },
    { symbol = "T", next_state = "B" },
    { symbol = "U", next_state = "B" },
    { symbol = "V", next_state = "B" },
    { symbol = "W", next_state = "B" },
    { symbol = "X", next_state = "B" },
    { symbol = "Y", next_state = "B" },
    { symbol = "Z", next_state = "B" },
]